import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import SEO from './SEO';

const SolutionPage = () => {
    const { id } = useParams();
    const navigate = useNavigate();

    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [activeTab, setActiveTab] = useState('optimized');

    useEffect(() => {
        const fetchSolution = async () => {
            setLoading(true);
            setError('');
            try {
                const API_BASE = import.meta.env.VITE_API_URL || '';
                const response = await axios.get(`${API_BASE}/api/solution/${id}`);
                setData(response.data);
            } catch (err) {
                console.error(err);
                if (err.response && err.response.status === 503) {
                    setError('AI Service is currently unavailable (API Key Missing).');
                } else {
                    setError('Failed to generate solution. Please try again later.');
                }
            } finally {
                setLoading(false);
            }
        };

        if (id) {
            fetchSolution();
        }
    }, [id]);

    return (
        <>
            <SEO
                title={data ? `Solution: ${data.title}` : 'Generating Solution...'}
                description={`AI Generated Solution for LeetCode ${id}`}
                path={`/solution/${id}`}
            />

            <div style={{ padding: '2rem 5%', minHeight: '90vh', maxWidth: '1000px', margin: '0 auto' }}>
                <button
                    onClick={() => navigate(-1)}
                    style={{
                        background: 'transparent', border: '1px solid #333', color: '#888',
                        padding: '0.5rem 1rem', borderRadius: '6px', cursor: 'pointer', marginBottom: '2rem',
                        display: 'flex', alignItems: 'center', gap: '0.5rem'
                    }}
                >
                    ← Back
                </button>

                {loading && (
                    <div style={{ textAlign: 'center', padding: '5rem', color: '#888' }}>
                        <div className="skeleton" style={{ width: '100%', height: '300px', marginBottom: '2rem' }}></div>
                        <h2>Generating optimized solutions for Question {id}...</h2>
                        <p style={{ opacity: 0.6 }}>This involves complex AI computation. Please wait roughly 5-10 seconds.</p>
                    </div>
                )}

                {error && (
                    <div style={{ textAlign: 'center', color: '#ff4444', marginTop: '4rem' }}>
                        <h2>Error</h2>
                        <p>{error}</p>
                        <button onClick={() => window.location.reload()} style={{ marginTop: '1rem', padding: '0.6rem 1.2rem', background: '#333', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer' }}>Try Again</button>
                    </div>
                )}

                {!loading && !error && data && data.solutions && (
                    <div className="solution-container" style={{ background: '#1a1a1a', borderRadius: '16px', border: '1px solid #333', overflow: 'hidden' }}>

                        {/* Header */}
                        <div style={{ padding: '2rem', borderBottom: '1px solid #333', background: 'rgba(255,255,255,0.02)' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem', alignItems: 'center' }}>
                                <div>
                                    <h1 style={{ fontSize: '2rem', margin: '0 0 0.5rem 0' }}>{data.title}</h1>
                                    <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                                        <span style={{ color: '#888' }}>Question #{id}</span>
                                        <span style={{
                                            color: data.source === 'cached' ? '#4caf50' : '#2196f3',
                                            background: data.source === 'cached' ? '#4caf5022' : '#2196f322',
                                            padding: '0.2rem 0.6rem', borderRadius: '4px', fontSize: '0.8rem', fontWeight: 'bold'
                                        }}>
                                            {data.source === 'cached' ? '⚡ From Saved Library' : '✨ Generated by AI'}
                                        </span>
                                    </div>
                                </div>

                                <a
                                    href={`https://leetcode.com/problems/${data.title.toLowerCase().replace(/ /g, '-')}`} // Basic slug guess, standard is usually consistent
                                    target="_blank"
                                    rel="noreferrer"
                                    style={{ color: '#ccc', textDecoration: 'underline', fontSize: '0.9rem' }}
                                >
                                    View on LeetCode ↗
                                </a>
                            </div>
                        </div>

                        {/* Tabs */}
                        <div style={{ padding: '0 2rem', borderBottom: '1px solid #333', marginTop: '1rem', display: 'flex', gap: '1rem', overflowX: 'auto' }}>
                            {['basic', 'optimized', 'best'].map(tab => (
                                <button
                                    key={tab}
                                    onClick={() => setActiveTab(tab)}
                                    style={{
                                        background: 'transparent',
                                        color: activeTab === tab ? 'var(--accent-orange)' : '#888',
                                        border: 'none',
                                        padding: '1rem 0.5rem',
                                        cursor: 'pointer',
                                        textTransform: 'capitalize',
                                        fontWeight: 'bold',
                                        fontSize: '1.1rem',
                                        borderBottom: activeTab === tab ? '3px solid var(--accent-orange)' : '3px solid transparent',
                                        transition: 'all 0.2s'
                                    }}
                                >
                                    {tab} Approach
                                </button>
                            ))}
                        </div>

                        {/* Content */}
                        <div style={{ padding: '2rem' }}>
                            <div style={{ display: 'flex', gap: '3rem', marginBottom: '2rem', flexWrap: 'wrap' }}>
                                <div style={{ background: '#222', padding: '1rem', borderRadius: '8px', minWidth: '150px' }}>
                                    <div style={{ color: '#888', fontSize: '0.9rem', marginBottom: '0.3rem' }}>Time Complexity</div>
                                    <div style={{ color: '#fff', fontSize: '1.2rem', fontWeight: 'bold' }}>{data.solutions[activeTab].time}</div>
                                </div>
                                <div style={{ background: '#222', padding: '1rem', borderRadius: '8px', minWidth: '150px' }}>
                                    <div style={{ color: '#888', fontSize: '0.9rem', marginBottom: '0.3rem' }}>Space Complexity</div>
                                    <div style={{ color: '#fff', fontSize: '1.2rem', fontWeight: 'bold' }}>{data.solutions[activeTab].space}</div>
                                </div>
                            </div>

                            <h3 style={{ color: '#eee', marginBottom: '1rem' }}>Explanation</h3>
                            <p style={{ lineHeight: '1.8', color: '#ccc', marginBottom: '2.5rem', whiteSpace: 'pre-wrap', fontSize: '1.05rem' }}>
                                {data.solutions[activeTab].explanation}
                            </p>

                            <h3 style={{ color: '#eee', marginBottom: '1rem' }}>Code (Python)</h3>
                            <div style={{ position: 'relative' }}>
                                <pre style={{
                                    background: '#0d0d0d', padding: '1.5rem', borderRadius: '12px',
                                    overflowX: 'auto', border: '1px solid #333', fontFamily: 'Consolas, monospace',
                                    fontSize: '1rem', color: '#a5b3ce', lineHeight: '1.5'
                                }}>
                                    <code>{data.solutions[activeTab].code}</code>
                                </pre>
                            </div>
                        </div>

                    </div>
                )}
            </div>
        </>
    );
};

export default SolutionPage;
