import React, { useState, useEffect } from 'react';
import axios from 'axios';

const SolutionModal = ({ isOpen, onClose, questionId, title }) => {
    if (!isOpen) return null;

    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [activeTab, setActiveTab] = useState('optimized'); // default

    useEffect(() => {
        const fetchSolution = async () => {
            setLoading(true);
            setError('');
            try {
                const API_BASE = import.meta.env.VITE_API_URL || '';
                const response = await axios.get(`${API_BASE}/api/solution/${questionId}`);
                setData(response.data);
            } catch (err) {
                console.error(err);
                if (err.response && err.response.status === 503) {
                    setError('AI Service is currently unavailable (API Key Missing).');
                } else {
                    setError('Failed to generate solution. Please try again later.');
                }
            } finally {
                setLoading(false);
            }
        };

        if (isOpen && questionId) {
            fetchSolution();
        }
    }, [isOpen, questionId]);

    const handleBackdropClick = (e) => {
        if (e.target === e.currentTarget) onClose();
    };

    return (
        <div style={{
            position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.8)', backdropFilter: 'blur(5px)',
            zIndex: 1000, display: 'flex', justifyContent: 'center', alignItems: 'center'
        }} onClick={handleBackdropClick}>

            <div style={{
                background: '#1a1a1a', width: '90%', maxWidth: '800px', maxHeight: '90vh',
                borderRadius: '16px', border: '1px solid #333', overflow: 'hidden',
                display: 'flex', flexDirection: 'column', boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)'
            }}>

                {/* Header */}
                <div style={{ padding: '1.5rem', borderBottom: '1px solid #333', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div>
                        <h2 style={{ margin: 0, fontSize: '1.5rem', color: 'white' }}>Solution: {title}</h2>
                        {data && (
                            <div style={{ marginTop: '0.5rem', fontSize: '0.8rem', display: 'flex', gap: '1rem' }}>
                                <span style={{
                                    color: data.source === 'cached' ? '#4caf50' : '#2196f3',
                                    background: data.source === 'cached' ? '#4caf5022' : '#2196f322',
                                    padding: '0.2rem 0.6rem', borderRadius: '4px'
                                }}>
                                    {data.source === 'cached' ? '⚡ From Saved Library' : '✨ Generated by AI (First Time)'}
                                </span>
                            </div>
                        )}
                    </div>
                    <button onClick={onClose} style={{ background: 'none', border: 'none', color: '#888', fontSize: '1.5rem', cursor: 'pointer' }}>×</button>
                </div>

                {/* Content */}
                <div style={{ padding: '1.5rem', overflowY: 'auto', flex: 1 }}>
                    {loading && (
                        <div style={{ textAlign: 'center', padding: '3rem', color: '#888' }}>
                            <div className="skeleton" style={{ width: '100%', height: '200px', marginBottom: '1rem' }}></div>
                            <p>Generating optimized solutions for you...</p>
                            <p style={{ fontSize: '0.8rem', opacity: 0.6 }}>This might take a few seconds.</p>
                        </div>
                    )}

                    {error && (
                        <div style={{ textAlign: 'center', padding: '3rem', color: '#ff4444' }}>
                            <p>{error}</p>
                            <button onClick={onClose} style={{ marginTop: '1rem', padding: '0.5rem 1rem', background: '#333', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer' }}>Close</button>
                        </div>
                    )}

                    {!loading && !error && data && data.solutions && (
                        <>
                            {/* Tabs */}
                            <div style={{ display: 'flex', gap: '1rem', borderBottom: '1px solid #333', marginBottom: '1.5rem' }}>
                                {['basic', 'optimized', 'best'].map(tab => (
                                    <button
                                        key={tab}
                                        onClick={() => setActiveTab(tab)}
                                        style={{
                                            background: activeTab === tab ? '#333' : 'transparent',
                                            color: activeTab === tab ? 'white' : '#888',
                                            border: 'none', padding: '0.8rem 1.5rem', borderRadius: '8px 8px 0 0',
                                            cursor: 'pointer', textTransform: 'capitalize', fontWeight: 'bold',
                                            borderBottom: activeTab === tab ? '2px solid var(--accent-orange)' : '2px solid transparent'
                                        }}
                                    >
                                        {tab} Approach
                                    </button>
                                ))}
                            </div>

                            {/* Active Tab Content */}
                            <div>
                                <div style={{ display: 'flex', gap: '2rem', marginBottom: '1rem' }}>
                                    <div style={{ color: '#ccc' }}><strong>Time:</strong> <span style={{ color: '#fff' }}>{data.solutions[activeTab].time}</span></div>
                                    <div style={{ color: '#ccc' }}><strong>Space:</strong> <span style={{ color: '#fff' }}>{data.solutions[activeTab].space}</span></div>
                                </div>

                                <p style={{ lineHeight: '1.6', color: '#ddd', marginBottom: '1.5rem' }}>
                                    {data.solutions[activeTab].explanation}
                                </p>

                                <div style={{ position: 'relative' }}>
                                    <pre style={{
                                        background: '#111', padding: '1.5rem', borderRadius: '8px',
                                        overflowX: 'auto', border: '1px solid #333', fontFamily: 'monospace',
                                        fontSize: '0.9rem', color: '#a5b3ce'
                                    }}>
                                        <code>{data.solutions[activeTab].code}</code>
                                    </pre>
                                </div>
                            </div>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
};

export default SolutionModal;
